# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_abrenv')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_abrenv')
    _abrenv = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_abrenv', [dirname(__file__)])
        except ImportError:
            import _abrenv
            return _abrenv
        try:
            _mod = imp.load_module('_abrenv', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _abrenv = swig_import_helper()
    del swig_import_helper
else:
    import _abrenv
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _abrenv.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _abrenv.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _abrenv.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _abrenv.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _abrenv.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _abrenv.SwigPyIterator_equal(self, x)

    def copy(self):
        return _abrenv.SwigPyIterator_copy(self)

    def next(self):
        return _abrenv.SwigPyIterator_next(self)

    def __next__(self):
        return _abrenv.SwigPyIterator___next__(self)

    def previous(self):
        return _abrenv.SwigPyIterator_previous(self)

    def advance(self, n):
        return _abrenv.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _abrenv.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _abrenv.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _abrenv.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _abrenv.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _abrenv.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _abrenv.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _abrenv.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _abrenv.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _abrenv.vectori___nonzero__(self)

    def __bool__(self):
        return _abrenv.vectori___bool__(self)

    def __len__(self):
        return _abrenv.vectori___len__(self)

    def __getslice__(self, i, j):
        return _abrenv.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _abrenv.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _abrenv.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _abrenv.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _abrenv.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _abrenv.vectori___setitem__(self, *args)

    def pop(self):
        return _abrenv.vectori_pop(self)

    def append(self, x):
        return _abrenv.vectori_append(self, x)

    def empty(self):
        return _abrenv.vectori_empty(self)

    def size(self):
        return _abrenv.vectori_size(self)

    def swap(self, v):
        return _abrenv.vectori_swap(self, v)

    def begin(self):
        return _abrenv.vectori_begin(self)

    def end(self):
        return _abrenv.vectori_end(self)

    def rbegin(self):
        return _abrenv.vectori_rbegin(self)

    def rend(self):
        return _abrenv.vectori_rend(self)

    def clear(self):
        return _abrenv.vectori_clear(self)

    def get_allocator(self):
        return _abrenv.vectori_get_allocator(self)

    def pop_back(self):
        return _abrenv.vectori_pop_back(self)

    def erase(self, *args):
        return _abrenv.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _abrenv.new_vectori(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _abrenv.vectori_push_back(self, x)

    def front(self):
        return _abrenv.vectori_front(self)

    def back(self):
        return _abrenv.vectori_back(self)

    def assign(self, n, x):
        return _abrenv.vectori_assign(self, n, x)

    def resize(self, *args):
        return _abrenv.vectori_resize(self, *args)

    def insert(self, *args):
        return _abrenv.vectori_insert(self, *args)

    def reserve(self, n):
        return _abrenv.vectori_reserve(self, n)

    def capacity(self):
        return _abrenv.vectori_capacity(self)
    __swig_destroy__ = _abrenv.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _abrenv.vectori_swigregister
vectori_swigregister(vectori)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _abrenv.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _abrenv.vectord___nonzero__(self)

    def __bool__(self):
        return _abrenv.vectord___bool__(self)

    def __len__(self):
        return _abrenv.vectord___len__(self)

    def __getslice__(self, i, j):
        return _abrenv.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _abrenv.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _abrenv.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _abrenv.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _abrenv.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _abrenv.vectord___setitem__(self, *args)

    def pop(self):
        return _abrenv.vectord_pop(self)

    def append(self, x):
        return _abrenv.vectord_append(self, x)

    def empty(self):
        return _abrenv.vectord_empty(self)

    def size(self):
        return _abrenv.vectord_size(self)

    def swap(self, v):
        return _abrenv.vectord_swap(self, v)

    def begin(self):
        return _abrenv.vectord_begin(self)

    def end(self):
        return _abrenv.vectord_end(self)

    def rbegin(self):
        return _abrenv.vectord_rbegin(self)

    def rend(self):
        return _abrenv.vectord_rend(self)

    def clear(self):
        return _abrenv.vectord_clear(self)

    def get_allocator(self):
        return _abrenv.vectord_get_allocator(self)

    def pop_back(self):
        return _abrenv.vectord_pop_back(self)

    def erase(self, *args):
        return _abrenv.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _abrenv.new_vectord(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _abrenv.vectord_push_back(self, x)

    def front(self):
        return _abrenv.vectord_front(self)

    def back(self):
        return _abrenv.vectord_back(self)

    def assign(self, n, x):
        return _abrenv.vectord_assign(self, n, x)

    def resize(self, *args):
        return _abrenv.vectord_resize(self, *args)

    def insert(self, *args):
        return _abrenv.vectord_insert(self, *args)

    def reserve(self, n):
        return _abrenv.vectord_reserve(self, n)

    def capacity(self):
        return _abrenv.vectord_capacity(self)
    __swig_destroy__ = _abrenv.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _abrenv.vectord_swigregister
vectord_swigregister(vectord)

class Environment(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Environment, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Environment, name)
    __repr__ = _swig_repr

    def __init__(self, all_cooked_time, all_cooked_bw):
        this = _abrenv.new_Environment(all_cooked_time, all_cooked_bw)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def get_download_time(self, video_chunk_size):
        return _abrenv.Environment_get_download_time(self, video_chunk_size)

    def reset_download_time(self):
        return _abrenv.Environment_reset_download_time(self)

    def get_video_chunk(self, quality, delay_, sleep_time_, return_buffer_size_, rebuf_, video_chunk_size_, end_of_video_, video_chunk_remain_, video_chunk_vmaf_):
        return _abrenv.Environment_get_video_chunk(self, quality, delay_, sleep_time_, return_buffer_size_, rebuf_, video_chunk_size_, end_of_video_, video_chunk_remain_, video_chunk_vmaf_)
    __swig_setmethods__["all_cooked_bw"] = _abrenv.Environment_all_cooked_bw_set
    __swig_getmethods__["all_cooked_bw"] = _abrenv.Environment_all_cooked_bw_get
    if _newclass:
        all_cooked_bw = _swig_property(_abrenv.Environment_all_cooked_bw_get, _abrenv.Environment_all_cooked_bw_set)
    __swig_setmethods__["all_cooked_time"] = _abrenv.Environment_all_cooked_time_set
    __swig_getmethods__["all_cooked_time"] = _abrenv.Environment_all_cooked_time_get
    if _newclass:
        all_cooked_time = _swig_property(_abrenv.Environment_all_cooked_time_get, _abrenv.Environment_all_cooked_time_set)
    __swig_setmethods__["video_chunk_counter"] = _abrenv.Environment_video_chunk_counter_set
    __swig_getmethods__["video_chunk_counter"] = _abrenv.Environment_video_chunk_counter_get
    if _newclass:
        video_chunk_counter = _swig_property(_abrenv.Environment_video_chunk_counter_get, _abrenv.Environment_video_chunk_counter_set)
    __swig_setmethods__["buffer_size"] = _abrenv.Environment_buffer_size_set
    __swig_getmethods__["buffer_size"] = _abrenv.Environment_buffer_size_get
    if _newclass:
        buffer_size = _swig_property(_abrenv.Environment_buffer_size_get, _abrenv.Environment_buffer_size_set)
    __swig_setmethods__["trace_idx"] = _abrenv.Environment_trace_idx_set
    __swig_getmethods__["trace_idx"] = _abrenv.Environment_trace_idx_get
    if _newclass:
        trace_idx = _swig_property(_abrenv.Environment_trace_idx_get, _abrenv.Environment_trace_idx_set)
    __swig_setmethods__["cooked_time"] = _abrenv.Environment_cooked_time_set
    __swig_getmethods__["cooked_time"] = _abrenv.Environment_cooked_time_get
    if _newclass:
        cooked_time = _swig_property(_abrenv.Environment_cooked_time_get, _abrenv.Environment_cooked_time_set)
    __swig_setmethods__["cooked_bw"] = _abrenv.Environment_cooked_bw_set
    __swig_getmethods__["cooked_bw"] = _abrenv.Environment_cooked_bw_get
    if _newclass:
        cooked_bw = _swig_property(_abrenv.Environment_cooked_bw_get, _abrenv.Environment_cooked_bw_set)
    __swig_setmethods__["mahimahi_start_ptr"] = _abrenv.Environment_mahimahi_start_ptr_set
    __swig_getmethods__["mahimahi_start_ptr"] = _abrenv.Environment_mahimahi_start_ptr_get
    if _newclass:
        mahimahi_start_ptr = _swig_property(_abrenv.Environment_mahimahi_start_ptr_get, _abrenv.Environment_mahimahi_start_ptr_set)
    __swig_setmethods__["mahimahi_ptr"] = _abrenv.Environment_mahimahi_ptr_set
    __swig_getmethods__["mahimahi_ptr"] = _abrenv.Environment_mahimahi_ptr_get
    if _newclass:
        mahimahi_ptr = _swig_property(_abrenv.Environment_mahimahi_ptr_get, _abrenv.Environment_mahimahi_ptr_set)
    __swig_setmethods__["last_mahimahi_time"] = _abrenv.Environment_last_mahimahi_time_set
    __swig_getmethods__["last_mahimahi_time"] = _abrenv.Environment_last_mahimahi_time_get
    if _newclass:
        last_mahimahi_time = _swig_property(_abrenv.Environment_last_mahimahi_time_get, _abrenv.Environment_last_mahimahi_time_set)
    __swig_setmethods__["virtual_mahimahi_ptr"] = _abrenv.Environment_virtual_mahimahi_ptr_set
    __swig_getmethods__["virtual_mahimahi_ptr"] = _abrenv.Environment_virtual_mahimahi_ptr_get
    if _newclass:
        virtual_mahimahi_ptr = _swig_property(_abrenv.Environment_virtual_mahimahi_ptr_get, _abrenv.Environment_virtual_mahimahi_ptr_set)
    __swig_setmethods__["virtual_last_mahimahi_time"] = _abrenv.Environment_virtual_last_mahimahi_time_set
    __swig_getmethods__["virtual_last_mahimahi_time"] = _abrenv.Environment_virtual_last_mahimahi_time_get
    if _newclass:
        virtual_last_mahimahi_time = _swig_property(_abrenv.Environment_virtual_last_mahimahi_time_get, _abrenv.Environment_virtual_last_mahimahi_time_set)
    __swig_destroy__ = _abrenv.delete_Environment
    __del__ = lambda self: None
Environment_swigregister = _abrenv.Environment_swigregister
Environment_swigregister(Environment)

# This file is compatible with both classic and new-style classes.


